pipeline {
    agent { label 'master1' }

    stages {
        stage('Docker version') {
            steps {
                sh "echo $USER"
                sh 'docker version'
            }
        }
        stage('Delete workspace before build starts') {
            steps {
                echo 'Deleting workspace'
                deleteDir()
            }
        }
        stage('Checkout') {
            steps{
                git branch: 'main',
                    url: 'https://github.com/01Yura/Jenkins.git'        
                }
        }
        stage('Test') {
            steps{
                dir('Docker_image_jenkins') {
                    sh "ls -la "
                    sh "pwd"
                }
                    sh "ls -la "
                    sh "pwd"
            }
        }
        stage('Build docker image') {
            steps{
                dir('Docker_image_jenkins') {
                    sh 'docker build -t 01Yura/jenkins-image:2.0 .'
                }
            }
        }
        stage('Push docker image to DockerHub') {
            steps{
                withDockerRegistry(credentialsId: 'dockerhub-cred-yura', url: 'https://index.docker.io/v1/') {
                    sh '''
                        docker push 01Yura/jenkins-image:2.0
                    '''
                }
            }
        }
        stage('Delete docker image locally') {
            steps{
                sh 'docker rmi 01Yura/jenkins-images:0.4'
            }
        }
    }
}